include(CMakeHDL)

macro(CMakeHDL_get_target_property output_var library property)
    if("${property}" STREQUAL "CMakeHDL_LIBRARY")
        if("${library}" STREQUAL "ext")
            set("${output_var}" FALSE)
        else()
            set("${output_var}" TRUE)
        endif()
    elseif("${property}" STREQUAL "MERGE_LIBRARIES")
        if("${library}" STREQUAL "lib1")
            set("${output_var}" "lib1a;lib1b")
        elseif("${library}" STREQUAL "lib1a")
            set("${output_var}" "lib1a1;lib1a2")
        elseif("${library}" STREQUAL "lib1a1")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib1a2")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib1b")
            set("${output_var}" "lib1b1;lib1b2")
        elseif("${library}" STREQUAL "lib1b1")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib1b2")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib2")
            set("${output_var}" "lib2a;lib2b")
        elseif("${library}" STREQUAL "lib2a")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib2b")
            set("${output_var}" "lib2b1;lib2b2")
        elseif("${library}" STREQUAL "lib2b1")
            set("${output_var}" "")
        elseif("${library}" STREQUAL "lib2b2")
            set("${output_var}" "")
        else()
            message(FATAL_ERROR "mock got unexpected arguments: library=${library} property=${property}")
        endif()
    else()
        message(FATAL_ERROR "mock got unexpected arguments: library=${library} property=${property}")
    endif()
endmacro()

CMakeHDL_search_merge_libraries("lib1;lib2" output_var)

if(NOT "${output_var}" STREQUAL "lib1a1;lib1a2;lib1a;lib1b1;lib1b2;lib1b;lib1;lib2a;lib2b1;lib2b2;lib2b;lib2")
    message(FATAL_ERROR "unexpected output_var, got: \"${output_var}\"")
endif()